# For local development

version: '3.9'

services:
  app:
    ports:
      - "8000:8000"
    environment:
      SRC_API_RELOAD: "True"
      POSTGRES_HOST: "backend_school:5432"

  db:
    ports:
      - "5432:5432"
