version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
    image: pact-meridian:${PACT_MERIDIAN_VERSION:-latest}
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    environment:
      DB_POSTGRESS_HOST: "backend_school:5432"
    depends_on:
      db:
        condition: service_healthy

  node:
    image: node:20
    restart: always
    user: "node"
    working_dir: /var/www/frontend/server
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - "3000:3000"
    command: sh -c "node ./index.mjs"

  #nginx:
  #  image: nginx:latest
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./nginx/conf.d:/etc/nginx/conf.d
  #    - ./nginx/static:/var/www/static
  #    - ./nginx/cert:/etc/nginx/cert
  #  depends_on:
  #    - app
  #    - node

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - app
      - node

  db:
    image: postgres:13.4-buster
    hostname: backend_school
    container_name: backend_postgres
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "Studyhard1234."
      POSTGRES_USER: "firstuser"
      POSTGRES_DB: "backend_school"
    restart: always
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - firstuser  # Changed from backend_school to firstuser to reflect the actual role name
        - -d
        - backend_school
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  calender-backend:
    name: calender-backend
